server:
  port: 9000

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    hibernate:
      ddl-auto: 'update'
      use-new-id-generator-mappings: false

springdoc:
  swagger-ui:
    path: /swagger
    operations-sorter: method

datasource:
  master:
    jdbc-url: [your jdbc-url]
    username: [your username]
    password: [your password]
  slave:
    jdbc-url: [your jdbc-url]
    username: [your username]
    password: [your password]