server:
  port: 9000

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    hibernate:
      ddl-auto: 'update'
      use-new-id-generator-mappings: false
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
            revision_field_name: rev
            store_data_at_delete: true

springdoc:
  swagger-ui:
    path: /swagger
    operations-sorter: alpha
    tags-sorter: alpha

datasource:
  master:
    jdbc-url: jdbc:mysql://localhost:3306/jessy
    username: root
    password: 1234
    connection-test-query: SELECT 1
    maximum-pool-size: 4
  slave:
    jdbc-url: jdbc:mysql://localhost:3306/jessy
    username: root
    password: 1234
    connection-test-query: SELECT 2
    maximum-pool-size: 4

jwt:
  secret: secret
  access:
    name: access
    valid: 3600000 #1hour
  refresh:
    name: refresh
    valid: 2592000000 #30days