server:
  port: 9000

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: [url]
    username: [username]
    password: [password]
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    hibernate:
      ddl-auto: 'update'
      use-new-id-generator-mappings: false